/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KhachHangRouteImport } from './routes/khach-hang'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PortalTimesheetRouteImport } from './routes/portal.timesheet'
import { Route as PortalMyTreatmentsRouteImport } from './routes/portal.my-treatments'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalContentRouteImport } from './routes/portal.content'
import { Route as PortalContactsRouteImport } from './routes/portal.contacts'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as PortalAffiliateRouteImport } from './routes/portal.affiliate'
import { Route as KhachHangQrRouteImport } from './routes/khach-hang.qr'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNewsRouteImport } from './routes/app.news'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AdminVoucherRouteImport } from './routes/admin.voucher'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'
import { Route as AdminToursRouteImport } from './routes/admin.tours'
import { Route as AdminShiftsRouteImport } from './routes/admin.shifts'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminPageRouteImport } from './routes/admin.$page'
import { Route as PublicWalletRouteImport } from './routes/_public.wallet'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicProductsRouteImport } from './routes/_public.products'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicLookupRouteImport } from './routes/_public.lookup'
import { Route as PublicEventsRouteImport } from './routes/_public.events'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicCommunityRouteImport } from './routes/_public.community'
import { Route as PublicBookingRouteImport } from './routes/_public.booking'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicServicesIndexRouteImport } from './routes/_public.services.index'
import { Route as PublicProductsIndexRouteImport } from './routes/_public.products.index'
import { Route as PublicNewsIndexRouteImport } from './routes/_public.news.index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public.about.index'
import { Route as AppStoreCheckoutRouteImport } from './routes/app.store.checkout'
import { Route as AppStoreProductIdRouteImport } from './routes/app.store.$productId'
import { Route as AppNewsIdRouteImport } from './routes/app.news.$id'
import { Route as AppEventsIdRouteImport } from './routes/app.events.$id'
import { Route as ApiPublicSeedDemoTechnicianRouteImport } from './routes/api/public/seed-demo-technician'
import { Route as ApiPublicSeedDemoEmployeesRouteImport } from './routes/api/public/seed-demo-employees'
import { Route as ApiPublicSeedDemoCustomerRouteImport } from './routes/api/public/seed-demo-customer'
import { Route as ApiPublicLookupTreatmentsRouteImport } from './routes/api/public/lookup-treatments'
import { Route as PublicServicesIdRouteImport } from './routes/_public.services.$id'
import { Route as PublicProductsTechnologyTransferRouteImport } from './routes/_public.products.technology-transfer'
import { Route as PublicProductsServicesRouteImport } from './routes/_public.products.services'
import { Route as PublicProductsMachinesRouteImport } from './routes/_public.products.machines'
import { Route as PublicProductsAccessoriesRouteImport } from './routes/_public.products.accessories'
import { Route as PublicProductsIdRouteImport } from './routes/_public.products.$id'
import { Route as PublicNewsTrainingRouteImport } from './routes/_public.news.training'
import { Route as PublicNewsEventsRouteImport } from './routes/_public.news.events'
import { Route as PublicNewsActivitiesRouteImport } from './routes/_public.news.activities'
import { Route as PublicNewsIdRouteImport } from './routes/_public.news.$id'
import { Route as PublicEventsIdRouteImport } from './routes/_public.events.$id'
import { Route as PublicAboutTestimonialsRouteImport } from './routes/_public.about.testimonials'
import { Route as PublicAboutTeamRouteImport } from './routes/_public.about.team'
import { Route as PublicAboutHistoryRouteImport } from './routes/_public.about.history'
import { Route as PublicAboutCertificationsRouteImport } from './routes/_public.about.certifications'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangRoute = KhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PortalTimesheetRoute = PortalTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyTreatmentsRoute = PortalMyTreatmentsRouteImport.update({
  id: '/my-treatments',
  path: '/my-treatments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContentRoute = PortalContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAffiliateRoute = PortalAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => PortalRoute,
} as any)
const KhachHangQrRoute = KhachHangQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => KhachHangRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminVoucherRoute = AdminVoucherRouteImport.update({
  id: '/voucher',
  path: '/voucher',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShiftsRoute = AdminShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)
const PublicWalletRoute = PublicWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLookupRoute = PublicLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCommunityRoute = PublicCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingRoute = PublicBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesIndexRoute = PublicServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicServicesRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicAboutRoute,
} as any)
const AppStoreCheckoutRoute = AppStoreCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppStoreProductIdRoute = AppStoreProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppStoreRoute,
} as any)
const AppNewsIdRoute = AppNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppNewsRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEventsRoute,
} as any)
const ApiPublicSeedDemoTechnicianRoute =
  ApiPublicSeedDemoTechnicianRouteImport.update({
    id: '/api/public/seed-demo-technician',
    path: '/api/public/seed-demo-technician',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSeedDemoEmployeesRoute =
  ApiPublicSeedDemoEmployeesRouteImport.update({
    id: '/api/public/seed-demo-employees',
    path: '/api/public/seed-demo-employees',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSeedDemoCustomerRoute =
  ApiPublicSeedDemoCustomerRouteImport.update({
    id: '/api/public/seed-demo-customer',
    path: '/api/public/seed-demo-customer',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLookupTreatmentsRoute =
  ApiPublicLookupTreatmentsRouteImport.update({
    id: '/api/public/lookup-treatments',
    path: '/api/public/lookup-treatments',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicServicesIdRoute = PublicServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicServicesRoute,
} as any)
const PublicProductsTechnologyTransferRoute =
  PublicProductsTechnologyTransferRouteImport.update({
    id: '/technology-transfer',
    path: '/technology-transfer',
    getParentRoute: () => PublicProductsRoute,
  } as any)
const PublicProductsServicesRoute = PublicProductsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicProductsMachinesRoute = PublicProductsMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicProductsAccessoriesRoute =
  PublicProductsAccessoriesRouteImport.update({
    id: '/accessories',
    path: '/accessories',
    getParentRoute: () => PublicProductsRoute,
  } as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicNewsTrainingRoute = PublicNewsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicNewsEventsRoute = PublicNewsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicNewsActivitiesRoute = PublicNewsActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicNewsIdRoute = PublicNewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicEventsIdRoute = PublicEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicEventsRoute,
} as any)
const PublicAboutTestimonialsRoute = PublicAboutTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutTeamRoute = PublicAboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutHistoryRoute = PublicAboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutCertificationsRoute =
  PublicAboutCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => PublicAboutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/about': typeof PublicAboutRouteWithChildren
  '/booking': typeof PublicBookingRoute
  '/community': typeof PublicCommunityRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/lookup': typeof PublicLookupRoute
  '/news': typeof PublicNewsRouteWithChildren
  '/products': typeof PublicProductsRouteWithChildren
  '/services': typeof PublicServicesRouteWithChildren
  '/wallet': typeof PublicWalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/app/account': typeof AppAccountRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/news': typeof AppNewsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/khach-hang/qr': typeof KhachHangQrRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/about/certifications': typeof PublicAboutCertificationsRoute
  '/about/history': typeof PublicAboutHistoryRoute
  '/about/team': typeof PublicAboutTeamRoute
  '/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/events/$id': typeof PublicEventsIdRoute
  '/news/$id': typeof PublicNewsIdRoute
  '/news/activities': typeof PublicNewsActivitiesRoute
  '/news/events': typeof PublicNewsEventsRoute
  '/news/training': typeof PublicNewsTrainingRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products/accessories': typeof PublicProductsAccessoriesRoute
  '/products/machines': typeof PublicProductsMachinesRoute
  '/products/services': typeof PublicProductsServicesRoute
  '/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/services/$id': typeof PublicServicesIdRoute
  '/api/public/lookup-treatments': typeof ApiPublicLookupTreatmentsRoute
  '/api/public/seed-demo-customer': typeof ApiPublicSeedDemoCustomerRoute
  '/api/public/seed-demo-employees': typeof ApiPublicSeedDemoEmployeesRoute
  '/api/public/seed-demo-technician': typeof ApiPublicSeedDemoTechnicianRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/store/$productId': typeof AppStoreProductIdRoute
  '/app/store/checkout': typeof AppStoreCheckoutRoute
  '/about/': typeof PublicAboutIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/products/': typeof PublicProductsIndexRoute
  '/services/': typeof PublicServicesIndexRoute
}
export interface FileRoutesByTo {
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/booking': typeof PublicBookingRoute
  '/community': typeof PublicCommunityRoute
  '/contact': typeof PublicContactRoute
  '/events': typeof PublicEventsRouteWithChildren
  '/lookup': typeof PublicLookupRoute
  '/wallet': typeof PublicWalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/app/account': typeof AppAccountRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/news': typeof AppNewsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/khach-hang/qr': typeof KhachHangQrRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/about/certifications': typeof PublicAboutCertificationsRoute
  '/about/history': typeof PublicAboutHistoryRoute
  '/about/team': typeof PublicAboutTeamRoute
  '/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/events/$id': typeof PublicEventsIdRoute
  '/news/$id': typeof PublicNewsIdRoute
  '/news/activities': typeof PublicNewsActivitiesRoute
  '/news/events': typeof PublicNewsEventsRoute
  '/news/training': typeof PublicNewsTrainingRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products/accessories': typeof PublicProductsAccessoriesRoute
  '/products/machines': typeof PublicProductsMachinesRoute
  '/products/services': typeof PublicProductsServicesRoute
  '/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/services/$id': typeof PublicServicesIdRoute
  '/api/public/lookup-treatments': typeof ApiPublicLookupTreatmentsRoute
  '/api/public/seed-demo-customer': typeof ApiPublicSeedDemoCustomerRoute
  '/api/public/seed-demo-employees': typeof ApiPublicSeedDemoEmployeesRoute
  '/api/public/seed-demo-technician': typeof ApiPublicSeedDemoTechnicianRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/store/$productId': typeof AppStoreProductIdRoute
  '/app/store/checkout': typeof AppStoreCheckoutRoute
  '/about': typeof PublicAboutIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/products': typeof PublicProductsIndexRoute
  '/services': typeof PublicServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_public/about': typeof PublicAboutRouteWithChildren
  '/_public/booking': typeof PublicBookingRoute
  '/_public/community': typeof PublicCommunityRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/events': typeof PublicEventsRouteWithChildren
  '/_public/lookup': typeof PublicLookupRoute
  '/_public/news': typeof PublicNewsRouteWithChildren
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/_public/services': typeof PublicServicesRouteWithChildren
  '/_public/wallet': typeof PublicWalletRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shifts': typeof AdminShiftsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/admin/voucher': typeof AdminVoucherRoute
  '/app/account': typeof AppAccountRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/news': typeof AppNewsRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRouteWithChildren
  '/khach-hang/qr': typeof KhachHangQrRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/_public/about/certifications': typeof PublicAboutCertificationsRoute
  '/_public/about/history': typeof PublicAboutHistoryRoute
  '/_public/about/team': typeof PublicAboutTeamRoute
  '/_public/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/_public/events/$id': typeof PublicEventsIdRoute
  '/_public/news/$id': typeof PublicNewsIdRoute
  '/_public/news/activities': typeof PublicNewsActivitiesRoute
  '/_public/news/events': typeof PublicNewsEventsRoute
  '/_public/news/training': typeof PublicNewsTrainingRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_public/products/accessories': typeof PublicProductsAccessoriesRoute
  '/_public/products/machines': typeof PublicProductsMachinesRoute
  '/_public/products/services': typeof PublicProductsServicesRoute
  '/_public/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/_public/services/$id': typeof PublicServicesIdRoute
  '/api/public/lookup-treatments': typeof ApiPublicLookupTreatmentsRoute
  '/api/public/seed-demo-customer': typeof ApiPublicSeedDemoCustomerRoute
  '/api/public/seed-demo-employees': typeof ApiPublicSeedDemoEmployeesRoute
  '/api/public/seed-demo-technician': typeof ApiPublicSeedDemoTechnicianRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/app/news/$id': typeof AppNewsIdRoute
  '/app/store/$productId': typeof AppStoreProductIdRoute
  '/app/store/checkout': typeof AppStoreCheckoutRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
  '/_public/services/': typeof PublicServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/about'
    | '/booking'
    | '/community'
    | '/contact'
    | '/events'
    | '/lookup'
    | '/news'
    | '/products'
    | '/services'
    | '/wallet'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/tours'
    | '/admin/treatments'
    | '/admin/voucher'
    | '/app/account'
    | '/app/events'
    | '/app/news'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/khach-hang/qr'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/timesheet'
    | '/admin/'
    | '/app/'
    | '/about/certifications'
    | '/about/history'
    | '/about/team'
    | '/about/testimonials'
    | '/events/$id'
    | '/news/$id'
    | '/news/activities'
    | '/news/events'
    | '/news/training'
    | '/products/$id'
    | '/products/accessories'
    | '/products/machines'
    | '/products/services'
    | '/products/technology-transfer'
    | '/services/$id'
    | '/api/public/lookup-treatments'
    | '/api/public/seed-demo-customer'
    | '/api/public/seed-demo-employees'
    | '/api/public/seed-demo-technician'
    | '/app/events/$id'
    | '/app/news/$id'
    | '/app/store/$productId'
    | '/app/store/checkout'
    | '/about/'
    | '/news/'
    | '/products/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/booking'
    | '/community'
    | '/contact'
    | '/events'
    | '/lookup'
    | '/wallet'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/tours'
    | '/admin/treatments'
    | '/admin/voucher'
    | '/app/account'
    | '/app/events'
    | '/app/news'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/khach-hang/qr'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/timesheet'
    | '/'
    | '/admin'
    | '/app'
    | '/about/certifications'
    | '/about/history'
    | '/about/team'
    | '/about/testimonials'
    | '/events/$id'
    | '/news/$id'
    | '/news/activities'
    | '/news/events'
    | '/news/training'
    | '/products/$id'
    | '/products/accessories'
    | '/products/machines'
    | '/products/services'
    | '/products/technology-transfer'
    | '/services/$id'
    | '/api/public/lookup-treatments'
    | '/api/public/seed-demo-customer'
    | '/api/public/seed-demo-employees'
    | '/api/public/seed-demo-technician'
    | '/app/events/$id'
    | '/app/news/$id'
    | '/app/store/$productId'
    | '/app/store/checkout'
    | '/about'
    | '/news'
    | '/products'
    | '/services'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/app'
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/_public/about'
    | '/_public/booking'
    | '/_public/community'
    | '/_public/contact'
    | '/_public/events'
    | '/_public/lookup'
    | '/_public/news'
    | '/_public/products'
    | '/_public/services'
    | '/_public/wallet'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/news'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shifts'
    | '/admin/tours'
    | '/admin/treatments'
    | '/admin/voucher'
    | '/app/account'
    | '/app/events'
    | '/app/news'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/khach-hang/qr'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/timesheet'
    | '/_public/'
    | '/admin/'
    | '/app/'
    | '/_public/about/certifications'
    | '/_public/about/history'
    | '/_public/about/team'
    | '/_public/about/testimonials'
    | '/_public/events/$id'
    | '/_public/news/$id'
    | '/_public/news/activities'
    | '/_public/news/events'
    | '/_public/news/training'
    | '/_public/products/$id'
    | '/_public/products/accessories'
    | '/_public/products/machines'
    | '/_public/products/services'
    | '/_public/products/technology-transfer'
    | '/_public/services/$id'
    | '/api/public/lookup-treatments'
    | '/api/public/seed-demo-customer'
    | '/api/public/seed-demo-employees'
    | '/api/public/seed-demo-technician'
    | '/app/events/$id'
    | '/app/news/$id'
    | '/app/store/$productId'
    | '/app/store/checkout'
    | '/_public/about/'
    | '/_public/news/'
    | '/_public/products/'
    | '/_public/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DangKyRoute: typeof DangKyRoute
  KhachHangRoute: typeof KhachHangRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiPublicLookupTreatmentsRoute: typeof ApiPublicLookupTreatmentsRoute
  ApiPublicSeedDemoCustomerRoute: typeof ApiPublicSeedDemoCustomerRoute
  ApiPublicSeedDemoEmployeesRoute: typeof ApiPublicSeedDemoEmployeesRoute
  ApiPublicSeedDemoTechnicianRoute: typeof ApiPublicSeedDemoTechnicianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang': {
      id: '/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof KhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/portal/timesheet': {
      id: '/portal/timesheet'
      path: '/timesheet'
      fullPath: '/portal/timesheet'
      preLoaderRoute: typeof PortalTimesheetRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/my-treatments': {
      id: '/portal/my-treatments'
      path: '/my-treatments'
      fullPath: '/portal/my-treatments'
      preLoaderRoute: typeof PortalMyTreatmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/content': {
      id: '/portal/content'
      path: '/content'
      fullPath: '/portal/content'
      preLoaderRoute: typeof PortalContentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/affiliate': {
      id: '/portal/affiliate'
      path: '/affiliate'
      fullPath: '/portal/affiliate'
      preLoaderRoute: typeof PortalAffiliateRouteImport
      parentRoute: typeof PortalRoute
    }
    '/khach-hang/qr': {
      id: '/khach-hang/qr'
      path: '/qr'
      fullPath: '/khach-hang/qr'
      preLoaderRoute: typeof KhachHangQrRouteImport
      parentRoute: typeof KhachHangRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/voucher': {
      id: '/admin/voucher'
      path: '/voucher'
      fullPath: '/admin/voucher'
      preLoaderRoute: typeof AdminVoucherRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shifts': {
      id: '/admin/shifts'
      path: '/shifts'
      fullPath: '/admin/shifts'
      preLoaderRoute: typeof AdminShiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/wallet': {
      id: '/_public/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof PublicWalletRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/lookup': {
      id: '/_public/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof PublicLookupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/community': {
      id: '/_public/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof PublicCommunityRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking': {
      id: '/_public/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof PublicBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services/': {
      id: '/_public/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof PublicServicesIndexRouteImport
      parentRoute: typeof PublicServicesRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/app/store/checkout': {
      id: '/app/store/checkout'
      path: '/checkout'
      fullPath: '/app/store/checkout'
      preLoaderRoute: typeof AppStoreCheckoutRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/app/store/$productId': {
      id: '/app/store/$productId'
      path: '/$productId'
      fullPath: '/app/store/$productId'
      preLoaderRoute: typeof AppStoreProductIdRouteImport
      parentRoute: typeof AppStoreRoute
    }
    '/app/news/$id': {
      id: '/app/news/$id'
      path: '/$id'
      fullPath: '/app/news/$id'
      preLoaderRoute: typeof AppNewsIdRouteImport
      parentRoute: typeof AppNewsRoute
    }
    '/app/events/$id': {
      id: '/app/events/$id'
      path: '/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/api/public/seed-demo-technician': {
      id: '/api/public/seed-demo-technician'
      path: '/api/public/seed-demo-technician'
      fullPath: '/api/public/seed-demo-technician'
      preLoaderRoute: typeof ApiPublicSeedDemoTechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo-employees': {
      id: '/api/public/seed-demo-employees'
      path: '/api/public/seed-demo-employees'
      fullPath: '/api/public/seed-demo-employees'
      preLoaderRoute: typeof ApiPublicSeedDemoEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo-customer': {
      id: '/api/public/seed-demo-customer'
      path: '/api/public/seed-demo-customer'
      fullPath: '/api/public/seed-demo-customer'
      preLoaderRoute: typeof ApiPublicSeedDemoCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lookup-treatments': {
      id: '/api/public/lookup-treatments'
      path: '/api/public/lookup-treatments'
      fullPath: '/api/public/lookup-treatments'
      preLoaderRoute: typeof ApiPublicLookupTreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/services/$id': {
      id: '/_public/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof PublicServicesIdRouteImport
      parentRoute: typeof PublicServicesRoute
    }
    '/_public/products/technology-transfer': {
      id: '/_public/products/technology-transfer'
      path: '/technology-transfer'
      fullPath: '/products/technology-transfer'
      preLoaderRoute: typeof PublicProductsTechnologyTransferRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/services': {
      id: '/_public/products/services'
      path: '/services'
      fullPath: '/products/services'
      preLoaderRoute: typeof PublicProductsServicesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/machines': {
      id: '/_public/products/machines'
      path: '/machines'
      fullPath: '/products/machines'
      preLoaderRoute: typeof PublicProductsMachinesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/accessories': {
      id: '/_public/products/accessories'
      path: '/accessories'
      fullPath: '/products/accessories'
      preLoaderRoute: typeof PublicProductsAccessoriesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/news/training': {
      id: '/_public/news/training'
      path: '/training'
      fullPath: '/news/training'
      preLoaderRoute: typeof PublicNewsTrainingRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/news/events': {
      id: '/_public/news/events'
      path: '/events'
      fullPath: '/news/events'
      preLoaderRoute: typeof PublicNewsEventsRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/news/activities': {
      id: '/_public/news/activities'
      path: '/activities'
      fullPath: '/news/activities'
      preLoaderRoute: typeof PublicNewsActivitiesRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/news/$id': {
      id: '/_public/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof PublicNewsIdRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/events/$id': {
      id: '/_public/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof PublicEventsIdRouteImport
      parentRoute: typeof PublicEventsRoute
    }
    '/_public/about/testimonials': {
      id: '/_public/about/testimonials'
      path: '/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof PublicAboutTestimonialsRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/team': {
      id: '/_public/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof PublicAboutTeamRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/history': {
      id: '/_public/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof PublicAboutHistoryRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/certifications': {
      id: '/_public/about/certifications'
      path: '/certifications'
      fullPath: '/about/certifications'
      preLoaderRoute: typeof PublicAboutCertificationsRouteImport
      parentRoute: typeof PublicAboutRoute
    }
  }
}

interface PublicAboutRouteChildren {
  PublicAboutCertificationsRoute: typeof PublicAboutCertificationsRoute
  PublicAboutHistoryRoute: typeof PublicAboutHistoryRoute
  PublicAboutTeamRoute: typeof PublicAboutTeamRoute
  PublicAboutTestimonialsRoute: typeof PublicAboutTestimonialsRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
}

const PublicAboutRouteChildren: PublicAboutRouteChildren = {
  PublicAboutCertificationsRoute: PublicAboutCertificationsRoute,
  PublicAboutHistoryRoute: PublicAboutHistoryRoute,
  PublicAboutTeamRoute: PublicAboutTeamRoute,
  PublicAboutTestimonialsRoute: PublicAboutTestimonialsRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
}

const PublicAboutRouteWithChildren = PublicAboutRoute._addFileChildren(
  PublicAboutRouteChildren,
)

interface PublicEventsRouteChildren {
  PublicEventsIdRoute: typeof PublicEventsIdRoute
}

const PublicEventsRouteChildren: PublicEventsRouteChildren = {
  PublicEventsIdRoute: PublicEventsIdRoute,
}

const PublicEventsRouteWithChildren = PublicEventsRoute._addFileChildren(
  PublicEventsRouteChildren,
)

interface PublicNewsRouteChildren {
  PublicNewsIdRoute: typeof PublicNewsIdRoute
  PublicNewsActivitiesRoute: typeof PublicNewsActivitiesRoute
  PublicNewsEventsRoute: typeof PublicNewsEventsRoute
  PublicNewsTrainingRoute: typeof PublicNewsTrainingRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
}

const PublicNewsRouteChildren: PublicNewsRouteChildren = {
  PublicNewsIdRoute: PublicNewsIdRoute,
  PublicNewsActivitiesRoute: PublicNewsActivitiesRoute,
  PublicNewsEventsRoute: PublicNewsEventsRoute,
  PublicNewsTrainingRoute: PublicNewsTrainingRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
}

const PublicNewsRouteWithChildren = PublicNewsRoute._addFileChildren(
  PublicNewsRouteChildren,
)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
  PublicProductsAccessoriesRoute: typeof PublicProductsAccessoriesRoute
  PublicProductsMachinesRoute: typeof PublicProductsMachinesRoute
  PublicProductsServicesRoute: typeof PublicProductsServicesRoute
  PublicProductsTechnologyTransferRoute: typeof PublicProductsTechnologyTransferRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
  PublicProductsAccessoriesRoute: PublicProductsAccessoriesRoute,
  PublicProductsMachinesRoute: PublicProductsMachinesRoute,
  PublicProductsServicesRoute: PublicProductsServicesRoute,
  PublicProductsTechnologyTransferRoute: PublicProductsTechnologyTransferRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicServicesRouteChildren {
  PublicServicesIdRoute: typeof PublicServicesIdRoute
  PublicServicesIndexRoute: typeof PublicServicesIndexRoute
}

const PublicServicesRouteChildren: PublicServicesRouteChildren = {
  PublicServicesIdRoute: PublicServicesIdRoute,
  PublicServicesIndexRoute: PublicServicesIndexRoute,
}

const PublicServicesRouteWithChildren = PublicServicesRoute._addFileChildren(
  PublicServicesRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRouteWithChildren
  PublicBookingRoute: typeof PublicBookingRoute
  PublicCommunityRoute: typeof PublicCommunityRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicEventsRoute: typeof PublicEventsRouteWithChildren
  PublicLookupRoute: typeof PublicLookupRoute
  PublicNewsRoute: typeof PublicNewsRouteWithChildren
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicServicesRoute: typeof PublicServicesRouteWithChildren
  PublicWalletRoute: typeof PublicWalletRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRouteWithChildren,
  PublicBookingRoute: PublicBookingRoute,
  PublicCommunityRoute: PublicCommunityRoute,
  PublicContactRoute: PublicContactRoute,
  PublicEventsRoute: PublicEventsRouteWithChildren,
  PublicLookupRoute: PublicLookupRoute,
  PublicNewsRoute: PublicNewsRouteWithChildren,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicServicesRoute: PublicServicesRouteWithChildren,
  PublicWalletRoute: PublicWalletRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShiftsRoute: typeof AdminShiftsRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminVoucherRoute: typeof AdminVoucherRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShiftsRoute: AdminShiftsRoute,
  AdminToursRoute: AdminToursRoute,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminVoucherRoute: AdminVoucherRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEventsRouteChildren {
  AppEventsIdRoute: typeof AppEventsIdRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsIdRoute: AppEventsIdRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppNewsRouteChildren {
  AppNewsIdRoute: typeof AppNewsIdRoute
}

const AppNewsRouteChildren: AppNewsRouteChildren = {
  AppNewsIdRoute: AppNewsIdRoute,
}

const AppNewsRouteWithChildren =
  AppNewsRoute._addFileChildren(AppNewsRouteChildren)

interface AppStoreRouteChildren {
  AppStoreProductIdRoute: typeof AppStoreProductIdRoute
  AppStoreCheckoutRoute: typeof AppStoreCheckoutRoute
}

const AppStoreRouteChildren: AppStoreRouteChildren = {
  AppStoreProductIdRoute: AppStoreProductIdRoute,
  AppStoreCheckoutRoute: AppStoreCheckoutRoute,
}

const AppStoreRouteWithChildren = AppStoreRoute._addFileChildren(
  AppStoreRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppNewsRoute: typeof AppNewsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppScanRoute: typeof AppScanRoute
  AppStoreRoute: typeof AppStoreRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppEventsRoute: AppEventsRouteWithChildren,
  AppNewsRoute: AppNewsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppScanRoute: AppScanRoute,
  AppStoreRoute: AppStoreRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KhachHangRouteChildren {
  KhachHangQrRoute: typeof KhachHangQrRoute
}

const KhachHangRouteChildren: KhachHangRouteChildren = {
  KhachHangQrRoute: KhachHangQrRoute,
}

const KhachHangRouteWithChildren = KhachHangRoute._addFileChildren(
  KhachHangRouteChildren,
)

interface PortalRouteChildren {
  PortalAffiliateRoute: typeof PortalAffiliateRoute
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalContactsRoute: typeof PortalContactsRoute
  PortalContentRoute: typeof PortalContentRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalMyTreatmentsRoute: typeof PortalMyTreatmentsRoute
  PortalTimesheetRoute: typeof PortalTimesheetRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAffiliateRoute: PortalAffiliateRoute,
  PortalBookingsRoute: PortalBookingsRoute,
  PortalContactsRoute: PortalContactsRoute,
  PortalContentRoute: PortalContentRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalMyTreatmentsRoute: PortalMyTreatmentsRoute,
  PortalTimesheetRoute: PortalTimesheetRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DangKyRoute: DangKyRoute,
  KhachHangRoute: KhachHangRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiPublicLookupTreatmentsRoute: ApiPublicLookupTreatmentsRoute,
  ApiPublicSeedDemoCustomerRoute: ApiPublicSeedDemoCustomerRoute,
  ApiPublicSeedDemoEmployeesRoute: ApiPublicSeedDemoEmployeesRoute,
  ApiPublicSeedDemoTechnicianRoute: ApiPublicSeedDemoTechnicianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
