/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KhachHangRouteImport } from './routes/khach-hang'
import { Route as DangKyRouteImport } from './routes/dang-ky'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PortalTimesheetRouteImport } from './routes/portal.timesheet'
import { Route as PortalProductsRouteImport } from './routes/portal.products'
import { Route as PortalMyTreatmentsRouteImport } from './routes/portal.my-treatments'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as PortalContentRouteImport } from './routes/portal.content'
import { Route as PortalContactsRouteImport } from './routes/portal.contacts'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as PortalAffiliateRouteImport } from './routes/portal.affiliate'
import { Route as AppStoreRouteImport } from './routes/app.store'
import { Route as AppScanRouteImport } from './routes/app.scan'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AdminTreatmentsRouteImport } from './routes/admin.treatments'
import { Route as AdminToursRouteImport } from './routes/admin.tours'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminPageRouteImport } from './routes/admin.$page'
import { Route as PublicProductsRouteImport } from './routes/_public.products'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicLookupRouteImport } from './routes/_public.lookup'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicBookingRouteImport } from './routes/_public.booking'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicProductsIndexRouteImport } from './routes/_public.products.index'
import { Route as PublicNewsIndexRouteImport } from './routes/_public.news.index'
import { Route as PublicAboutIndexRouteImport } from './routes/_public.about.index'
import { Route as PublicProductsTechnologyTransferRouteImport } from './routes/_public.products.technology-transfer'
import { Route as PublicProductsServicesRouteImport } from './routes/_public.products.services'
import { Route as PublicProductsMachinesRouteImport } from './routes/_public.products.machines'
import { Route as PublicProductsAccessoriesRouteImport } from './routes/_public.products.accessories'
import { Route as PublicProductsIdRouteImport } from './routes/_public.products.$id'
import { Route as PublicNewsTrainingRouteImport } from './routes/_public.news.training'
import { Route as PublicNewsEventsRouteImport } from './routes/_public.news.events'
import { Route as PublicNewsActivitiesRouteImport } from './routes/_public.news.activities'
import { Route as PublicAboutTestimonialsRouteImport } from './routes/_public.about.testimonials'
import { Route as PublicAboutTeamRouteImport } from './routes/_public.about.team'
import { Route as PublicAboutHistoryRouteImport } from './routes/_public.about.history'
import { Route as PublicAboutCertificationsRouteImport } from './routes/_public.about.certifications'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KhachHangRoute = KhachHangRouteImport.update({
  id: '/khach-hang',
  path: '/khach-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyRoute = DangKyRouteImport.update({
  id: '/dang-ky',
  path: '/dang-ky',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PortalTimesheetRoute = PortalTimesheetRouteImport.update({
  id: '/timesheet',
  path: '/timesheet',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMyTreatmentsRoute = PortalMyTreatmentsRouteImport.update({
  id: '/my-treatments',
  path: '/my-treatments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContentRoute = PortalContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContactsRoute = PortalContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAffiliateRoute = PortalAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => PortalRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminTreatmentsRoute = AdminTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)
const PublicProductsRoute = PublicProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLookupRoute = PublicLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookingRoute = PublicBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProductsIndexRoute = PublicProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicNewsIndexRoute = PublicNewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicAboutIndexRoute = PublicAboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicProductsTechnologyTransferRoute =
  PublicProductsTechnologyTransferRouteImport.update({
    id: '/technology-transfer',
    path: '/technology-transfer',
    getParentRoute: () => PublicProductsRoute,
  } as any)
const PublicProductsServicesRoute = PublicProductsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicProductsMachinesRoute = PublicProductsMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicProductsAccessoriesRoute =
  PublicProductsAccessoriesRouteImport.update({
    id: '/accessories',
    path: '/accessories',
    getParentRoute: () => PublicProductsRoute,
  } as any)
const PublicProductsIdRoute = PublicProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicProductsRoute,
} as any)
const PublicNewsTrainingRoute = PublicNewsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicNewsEventsRoute = PublicNewsEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicNewsActivitiesRoute = PublicNewsActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => PublicNewsRoute,
} as any)
const PublicAboutTestimonialsRoute = PublicAboutTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutTeamRoute = PublicAboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutHistoryRoute = PublicAboutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PublicAboutRoute,
} as any)
const PublicAboutCertificationsRoute =
  PublicAboutCertificationsRouteImport.update({
    id: '/certifications',
    path: '/certifications',
    getParentRoute: () => PublicAboutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/about': typeof PublicAboutRouteWithChildren
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/lookup': typeof PublicLookupRoute
  '/news': typeof PublicNewsRouteWithChildren
  '/products': typeof PublicProductsRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/app/account': typeof AppAccountRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/about/certifications': typeof PublicAboutCertificationsRoute
  '/about/history': typeof PublicAboutHistoryRoute
  '/about/team': typeof PublicAboutTeamRoute
  '/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/news/activities': typeof PublicNewsActivitiesRoute
  '/news/events': typeof PublicNewsEventsRoute
  '/news/training': typeof PublicNewsTrainingRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products/accessories': typeof PublicProductsAccessoriesRoute
  '/products/machines': typeof PublicProductsMachinesRoute
  '/products/services': typeof PublicProductsServicesRoute
  '/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/about/': typeof PublicAboutIndexRoute
  '/news/': typeof PublicNewsIndexRoute
  '/products/': typeof PublicProductsIndexRoute
}
export interface FileRoutesByTo {
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/booking': typeof PublicBookingRoute
  '/contact': typeof PublicContactRoute
  '/lookup': typeof PublicLookupRoute
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/app/account': typeof AppAccountRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/about/certifications': typeof PublicAboutCertificationsRoute
  '/about/history': typeof PublicAboutHistoryRoute
  '/about/team': typeof PublicAboutTeamRoute
  '/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/news/activities': typeof PublicNewsActivitiesRoute
  '/news/events': typeof PublicNewsEventsRoute
  '/news/training': typeof PublicNewsTrainingRoute
  '/products/$id': typeof PublicProductsIdRoute
  '/products/accessories': typeof PublicProductsAccessoriesRoute
  '/products/machines': typeof PublicProductsMachinesRoute
  '/products/services': typeof PublicProductsServicesRoute
  '/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/about': typeof PublicAboutIndexRoute
  '/news': typeof PublicNewsIndexRoute
  '/products': typeof PublicProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/dang-ky': typeof DangKyRoute
  '/khach-hang': typeof KhachHangRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_public/about': typeof PublicAboutRouteWithChildren
  '/_public/booking': typeof PublicBookingRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/lookup': typeof PublicLookupRoute
  '/_public/news': typeof PublicNewsRouteWithChildren
  '/_public/products': typeof PublicProductsRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/treatments': typeof AdminTreatmentsRoute
  '/app/account': typeof AppAccountRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/scan': typeof AppScanRoute
  '/app/store': typeof AppStoreRoute
  '/portal/affiliate': typeof PortalAffiliateRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/contacts': typeof PortalContactsRoute
  '/portal/content': typeof PortalContentRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/my-treatments': typeof PortalMyTreatmentsRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/timesheet': typeof PortalTimesheetRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/_public/about/certifications': typeof PublicAboutCertificationsRoute
  '/_public/about/history': typeof PublicAboutHistoryRoute
  '/_public/about/team': typeof PublicAboutTeamRoute
  '/_public/about/testimonials': typeof PublicAboutTestimonialsRoute
  '/_public/news/activities': typeof PublicNewsActivitiesRoute
  '/_public/news/events': typeof PublicNewsEventsRoute
  '/_public/news/training': typeof PublicNewsTrainingRoute
  '/_public/products/$id': typeof PublicProductsIdRoute
  '/_public/products/accessories': typeof PublicProductsAccessoriesRoute
  '/_public/products/machines': typeof PublicProductsMachinesRoute
  '/_public/products/services': typeof PublicProductsServicesRoute
  '/_public/products/technology-transfer': typeof PublicProductsTechnologyTransferRoute
  '/_public/about/': typeof PublicAboutIndexRoute
  '/_public/news/': typeof PublicNewsIndexRoute
  '/_public/products/': typeof PublicProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/about'
    | '/booking'
    | '/contact'
    | '/lookup'
    | '/news'
    | '/products'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/treatments'
    | '/app/account'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/products'
    | '/portal/timesheet'
    | '/admin/'
    | '/app/'
    | '/about/certifications'
    | '/about/history'
    | '/about/team'
    | '/about/testimonials'
    | '/news/activities'
    | '/news/events'
    | '/news/training'
    | '/products/$id'
    | '/products/accessories'
    | '/products/machines'
    | '/products/services'
    | '/products/technology-transfer'
    | '/about/'
    | '/news/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/booking'
    | '/contact'
    | '/lookup'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/treatments'
    | '/app/account'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/products'
    | '/portal/timesheet'
    | '/'
    | '/admin'
    | '/app'
    | '/about/certifications'
    | '/about/history'
    | '/about/team'
    | '/about/testimonials'
    | '/news/activities'
    | '/news/events'
    | '/news/training'
    | '/products/$id'
    | '/products/accessories'
    | '/products/machines'
    | '/products/services'
    | '/products/technology-transfer'
    | '/about'
    | '/news'
    | '/products'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/app'
    | '/dang-ky'
    | '/khach-hang'
    | '/login'
    | '/portal'
    | '/_public/about'
    | '/_public/booking'
    | '/_public/contact'
    | '/_public/lookup'
    | '/_public/news'
    | '/_public/products'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/settings'
    | '/admin/tours'
    | '/admin/treatments'
    | '/app/account'
    | '/app/notifications'
    | '/app/scan'
    | '/app/store'
    | '/portal/affiliate'
    | '/portal/bookings'
    | '/portal/contacts'
    | '/portal/content'
    | '/portal/dashboard'
    | '/portal/my-treatments'
    | '/portal/products'
    | '/portal/timesheet'
    | '/_public/'
    | '/admin/'
    | '/app/'
    | '/_public/about/certifications'
    | '/_public/about/history'
    | '/_public/about/team'
    | '/_public/about/testimonials'
    | '/_public/news/activities'
    | '/_public/news/events'
    | '/_public/news/training'
    | '/_public/products/$id'
    | '/_public/products/accessories'
    | '/_public/products/machines'
    | '/_public/products/services'
    | '/_public/products/technology-transfer'
    | '/_public/about/'
    | '/_public/news/'
    | '/_public/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  DangKyRoute: typeof DangKyRoute
  KhachHangRoute: typeof KhachHangRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khach-hang': {
      id: '/khach-hang'
      path: '/khach-hang'
      fullPath: '/khach-hang'
      preLoaderRoute: typeof KhachHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-ky': {
      id: '/dang-ky'
      path: '/dang-ky'
      fullPath: '/dang-ky'
      preLoaderRoute: typeof DangKyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/portal/timesheet': {
      id: '/portal/timesheet'
      path: '/timesheet'
      fullPath: '/portal/timesheet'
      preLoaderRoute: typeof PortalTimesheetRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/my-treatments': {
      id: '/portal/my-treatments'
      path: '/my-treatments'
      fullPath: '/portal/my-treatments'
      preLoaderRoute: typeof PortalMyTreatmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/content': {
      id: '/portal/content'
      path: '/content'
      fullPath: '/portal/content'
      preLoaderRoute: typeof PortalContentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contacts': {
      id: '/portal/contacts'
      path: '/contacts'
      fullPath: '/portal/contacts'
      preLoaderRoute: typeof PortalContactsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/affiliate': {
      id: '/portal/affiliate'
      path: '/affiliate'
      fullPath: '/portal/affiliate'
      preLoaderRoute: typeof PortalAffiliateRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scan': {
      id: '/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/treatments': {
      id: '/admin/treatments'
      path: '/treatments'
      fullPath: '/admin/treatments'
      preLoaderRoute: typeof AdminTreatmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/products': {
      id: '/_public/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicProductsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/lookup': {
      id: '/_public/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof PublicLookupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/booking': {
      id: '/_public/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof PublicBookingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/products/': {
      id: '/_public/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicProductsIndexRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/news/': {
      id: '/_public/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof PublicNewsIndexRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/about/': {
      id: '/_public/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof PublicAboutIndexRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/products/technology-transfer': {
      id: '/_public/products/technology-transfer'
      path: '/technology-transfer'
      fullPath: '/products/technology-transfer'
      preLoaderRoute: typeof PublicProductsTechnologyTransferRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/services': {
      id: '/_public/products/services'
      path: '/services'
      fullPath: '/products/services'
      preLoaderRoute: typeof PublicProductsServicesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/machines': {
      id: '/_public/products/machines'
      path: '/machines'
      fullPath: '/products/machines'
      preLoaderRoute: typeof PublicProductsMachinesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/accessories': {
      id: '/_public/products/accessories'
      path: '/accessories'
      fullPath: '/products/accessories'
      preLoaderRoute: typeof PublicProductsAccessoriesRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/products/$id': {
      id: '/_public/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof PublicProductsIdRouteImport
      parentRoute: typeof PublicProductsRoute
    }
    '/_public/news/training': {
      id: '/_public/news/training'
      path: '/training'
      fullPath: '/news/training'
      preLoaderRoute: typeof PublicNewsTrainingRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/news/events': {
      id: '/_public/news/events'
      path: '/events'
      fullPath: '/news/events'
      preLoaderRoute: typeof PublicNewsEventsRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/news/activities': {
      id: '/_public/news/activities'
      path: '/activities'
      fullPath: '/news/activities'
      preLoaderRoute: typeof PublicNewsActivitiesRouteImport
      parentRoute: typeof PublicNewsRoute
    }
    '/_public/about/testimonials': {
      id: '/_public/about/testimonials'
      path: '/testimonials'
      fullPath: '/about/testimonials'
      preLoaderRoute: typeof PublicAboutTestimonialsRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/team': {
      id: '/_public/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof PublicAboutTeamRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/history': {
      id: '/_public/about/history'
      path: '/history'
      fullPath: '/about/history'
      preLoaderRoute: typeof PublicAboutHistoryRouteImport
      parentRoute: typeof PublicAboutRoute
    }
    '/_public/about/certifications': {
      id: '/_public/about/certifications'
      path: '/certifications'
      fullPath: '/about/certifications'
      preLoaderRoute: typeof PublicAboutCertificationsRouteImport
      parentRoute: typeof PublicAboutRoute
    }
  }
}

interface PublicAboutRouteChildren {
  PublicAboutCertificationsRoute: typeof PublicAboutCertificationsRoute
  PublicAboutHistoryRoute: typeof PublicAboutHistoryRoute
  PublicAboutTeamRoute: typeof PublicAboutTeamRoute
  PublicAboutTestimonialsRoute: typeof PublicAboutTestimonialsRoute
  PublicAboutIndexRoute: typeof PublicAboutIndexRoute
}

const PublicAboutRouteChildren: PublicAboutRouteChildren = {
  PublicAboutCertificationsRoute: PublicAboutCertificationsRoute,
  PublicAboutHistoryRoute: PublicAboutHistoryRoute,
  PublicAboutTeamRoute: PublicAboutTeamRoute,
  PublicAboutTestimonialsRoute: PublicAboutTestimonialsRoute,
  PublicAboutIndexRoute: PublicAboutIndexRoute,
}

const PublicAboutRouteWithChildren = PublicAboutRoute._addFileChildren(
  PublicAboutRouteChildren,
)

interface PublicNewsRouteChildren {
  PublicNewsActivitiesRoute: typeof PublicNewsActivitiesRoute
  PublicNewsEventsRoute: typeof PublicNewsEventsRoute
  PublicNewsTrainingRoute: typeof PublicNewsTrainingRoute
  PublicNewsIndexRoute: typeof PublicNewsIndexRoute
}

const PublicNewsRouteChildren: PublicNewsRouteChildren = {
  PublicNewsActivitiesRoute: PublicNewsActivitiesRoute,
  PublicNewsEventsRoute: PublicNewsEventsRoute,
  PublicNewsTrainingRoute: PublicNewsTrainingRoute,
  PublicNewsIndexRoute: PublicNewsIndexRoute,
}

const PublicNewsRouteWithChildren = PublicNewsRoute._addFileChildren(
  PublicNewsRouteChildren,
)

interface PublicProductsRouteChildren {
  PublicProductsIdRoute: typeof PublicProductsIdRoute
  PublicProductsAccessoriesRoute: typeof PublicProductsAccessoriesRoute
  PublicProductsMachinesRoute: typeof PublicProductsMachinesRoute
  PublicProductsServicesRoute: typeof PublicProductsServicesRoute
  PublicProductsTechnologyTransferRoute: typeof PublicProductsTechnologyTransferRoute
  PublicProductsIndexRoute: typeof PublicProductsIndexRoute
}

const PublicProductsRouteChildren: PublicProductsRouteChildren = {
  PublicProductsIdRoute: PublicProductsIdRoute,
  PublicProductsAccessoriesRoute: PublicProductsAccessoriesRoute,
  PublicProductsMachinesRoute: PublicProductsMachinesRoute,
  PublicProductsServicesRoute: PublicProductsServicesRoute,
  PublicProductsTechnologyTransferRoute: PublicProductsTechnologyTransferRoute,
  PublicProductsIndexRoute: PublicProductsIndexRoute,
}

const PublicProductsRouteWithChildren = PublicProductsRoute._addFileChildren(
  PublicProductsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRouteWithChildren
  PublicBookingRoute: typeof PublicBookingRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicLookupRoute: typeof PublicLookupRoute
  PublicNewsRoute: typeof PublicNewsRouteWithChildren
  PublicProductsRoute: typeof PublicProductsRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRouteWithChildren,
  PublicBookingRoute: PublicBookingRoute,
  PublicContactRoute: PublicContactRoute,
  PublicLookupRoute: PublicLookupRoute,
  PublicNewsRoute: PublicNewsRouteWithChildren,
  PublicProductsRoute: PublicProductsRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminTreatmentsRoute: typeof AdminTreatmentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminToursRoute: AdminToursRoute,
  AdminTreatmentsRoute: AdminTreatmentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppScanRoute: typeof AppScanRoute
  AppStoreRoute: typeof AppStoreRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppScanRoute: AppScanRoute,
  AppStoreRoute: AppStoreRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAffiliateRoute: typeof PortalAffiliateRoute
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalContactsRoute: typeof PortalContactsRoute
  PortalContentRoute: typeof PortalContentRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalMyTreatmentsRoute: typeof PortalMyTreatmentsRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalTimesheetRoute: typeof PortalTimesheetRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAffiliateRoute: PortalAffiliateRoute,
  PortalBookingsRoute: PortalBookingsRoute,
  PortalContactsRoute: PortalContactsRoute,
  PortalContentRoute: PortalContentRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalMyTreatmentsRoute: PortalMyTreatmentsRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalTimesheetRoute: PortalTimesheetRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  DangKyRoute: DangKyRoute,
  KhachHangRoute: KhachHangRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
