/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminPageRouteImport } from './routes/admin.$page'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPageRoute = AdminPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/$page': typeof AdminPageRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/posts': typeof AdminPostsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/posts'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/posts'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/admin/$page'
    | '/admin/banners'
    | '/admin/bookings'
    | '/admin/catalog'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/posts'
    | '/_public/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$page': {
      id: '/admin/$page'
      path: '/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof AdminPageRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminPageRoute: typeof AdminPageRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPageRoute: AdminPageRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
