
-- 1) commissions: prevent staff from self-approving or setting arbitrary amounts
DROP POLICY IF EXISTS "Staff insert commissions" ON public.commissions;
CREATE POLICY "Staff insert commissions"
ON public.commissions
FOR INSERT
TO authenticated
WITH CHECK (
  has_role(auth.uid(), 'admin'::app_role)
  OR (
    has_role(auth.uid(), 'staff'::app_role)
    AND staff_id = auth.uid()
    AND COALESCE(status, 'pending') = 'pending'
    AND COALESCE(amount, 0) = 0
  )
);

-- 2) staff_shifts: restrict self insert/update to pending only
DROP POLICY IF EXISTS "staff_shifts_self_insert" ON public.staff_shifts;
CREATE POLICY "staff_shifts_self_insert"
ON public.staff_shifts
FOR INSERT
TO authenticated
WITH CHECK (
  staff_id = auth.uid()
  AND COALESCE(status, 'pending') = 'pending'
);

DROP POLICY IF EXISTS "staff_shifts_self_update" ON public.staff_shifts;
CREATE POLICY "staff_shifts_self_update"
ON public.staff_shifts
FOR UPDATE
TO authenticated
USING (staff_id = auth.uid() AND COALESCE(status, 'pending') = 'pending')
WITH CHECK (staff_id = auth.uid() AND COALESCE(status, 'pending') = 'pending');

-- 3) customers: prevent self-tampering of internal CRM/affiliate fields
CREATE OR REPLACE FUNCTION public.customers_protect_internal_fields()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  is_privileged boolean;
BEGIN
  is_privileged := has_role(auth.uid(), 'admin'::app_role)
                OR has_role(auth.uid(), 'manager'::app_role)
                OR has_role(auth.uid(), 'staff'::app_role);
  IF is_privileged THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    -- Force-safe values on self-created customer rows
    NEW.referred_by := NULL;
    NEW.referred_at := NULL;
    NEW.ref_code := NULL;         -- will be regenerated by customers_assign_ref_code
    NEW.status := 'Đang chăm sóc';
    NEW.notes := NULL;
    NEW.note := NULL;
    NEW.source := COALESCE(NEW.source, 'self-signup');
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    -- Preserve internal CRM/affiliate fields against self-tampering
    NEW.referred_by := OLD.referred_by;
    NEW.referred_at := OLD.referred_at;
    NEW.ref_code := OLD.ref_code;
    NEW.status := OLD.status;
    NEW.notes := OLD.notes;
    NEW.note := OLD.note;
    NEW.source := OLD.source;
    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS customers_protect_internal_fields_ins ON public.customers;
CREATE TRIGGER customers_protect_internal_fields_ins
BEFORE INSERT ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.customers_protect_internal_fields();

DROP TRIGGER IF EXISTS customers_protect_internal_fields_upd ON public.customers;
CREATE TRIGGER customers_protect_internal_fields_upd
BEFORE UPDATE ON public.customers
FOR EACH ROW EXECUTE FUNCTION public.customers_protect_internal_fields();
